version: '3.8'

services:
  postgres:
    image: 1181.s.kuaicdn.cn:11818/docker.io/postgres:17.6
    ports:
      - "34179:5432"
    container_name: pg_api
    restart: unless-stopped
    environment:
      POSTGRES_USER: kuaicdn
      POSTGRES_PASSWORD: abcd001002
      POSTGRES_DB: machine_info
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: 1181.s.kuaicdn.cn:11818/docker.io/redis:7.4.1
    container_name: redis_gin
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  cmdb-api:
    build: .
    container_name: cmdb-api
    restart: always
    ports:
      - "34177:8080"
    environment:
      - GIN_MODE=release
      - DB_HOST=3417.s.kuaicdn.cn
      - DB_PORT=34179
      - DB_USER=kuaicdn
      - DB_PASSWORD=abcd001002
      - DB_NAME=machine_info
      - JWT_SECRET=your-super-long-secret-key-2025
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data: